restaurant/urls.py
from django.urls import path

from restaurant.views import (
    index,
    CookerListView,
    CookerDetailView,
    DishListView,
    DishDetailView,
    DishTypeListView,
    CookerCreationView,
    DishCreateView,
    DishTypeCreateView,
    CookerUpdateView, DishUpdateView,
)

urlpatterns = [
    path("", index.as_view(), name="index"),
    path("cooks/", CookerListView.as_view(), name="cook-list"),
    path("cook/<int:pk>/", CookerDetailView.as_view(), name="cook-detail"),
    path("cook/<int:pk>/update", CookerUpdateView.as_view(), name="cook-update"),
    path("cook/create/", CookerCreationView.as_view(), name="cook-create"),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dish/<int:pk>", DishDetailView.as_view(), name="dish-detail"),
    path("dish/<int:pk>/update", DishUpdateView.as_view(), name="dish-update"),
    path("dish/create/", DishCreateView.as_view(), name="dish-create"),
    path("dish_type/create/", DishTypeCreateView.as_view(), name="dish-type-create"),
    path("dish/types/", DishTypeListView.as_view(), name="dish-type-list"),
]

app_name = "restaurant"

restaurant_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("restaurant.urls", namespace="restaurant")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("accounts/", include("django.contrib.auth.urls"))
]

restaurant/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class DishType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Cooker(AbstractUser):
    years_of_experience = models.IntegerField(null=True)

    class Meta:
        ordering = ["username"]

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("restaurant:cook-detail", kwargs={"pk": self.pk})


class Dish(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE, related_name="dishes")
    cooks = models.ManyToManyField(Cooker, related_name="dishes")

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

restaurant/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from restaurant.models import Cooker, DishType, Dish


class CookerCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cooker
        fields = UserCreationForm.Meta.fields + ("years_of_experience",)

    def clean_years_of_experience(self):
        years = self.cleaned_data["years_of_experience"]
        if years > 75:
            raise ValidationError("You can`t be so old!")
        return years


class DishCreationForm(forms.ModelForm):
    dish_type = forms.ModelChoiceField(
        label="hello",
        queryset=DishType.objects.all(),
        widget=forms.Select
    )
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Dish
        fields = "__all__"


class DishTypeCreationForm(forms.ModelForm):
    class Meta:
        model = DishType
        fields = "__all__"


class CookerSearchForm(forms.Form):
    username = forms.CharField(
        required=True,
        max_length=255,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Enter cook name..."}
        )
    )


class DishSearchForm(forms.Form):
    name = forms.CharField(
        required=True,
        max_length=255,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Enter dish name..."}
        )
    )


class CookerDishesUpdateForm(forms.ModelForm):
    class Meta:
        model = Cooker
        fields = ["username"]


class DishUpdateForm(forms.ModelForm):
    class Meta:
        model = Dish
        fields = ["price"]

restaurant/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from restaurant.forms import CookerCreationForm, DishCreationForm, DishTypeCreationForm, CookerSearchForm, \
    DishSearchForm, CookerDishesUpdateForm, DishUpdateForm
from restaurant.models import Dish, Cooker, DishType


class index(generic.ListView):
    model = Cooker
    template_name = "restaurant/index.html"

    def get_context_data(self, **kwargs):
        context = super(index, self).get_context_data(**kwargs)
        context["num_dishes"] = Dish.objects.count()
        context["num_cooks"] = Cooker.objects.count()
        context["num_dish_types"] = DishType.objects.count()

        return context


class CookerListView(LoginRequiredMixin, generic.ListView):
    model = Cooker
    paginate_by = 2
    template_name = "restaurant/cook_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CookerListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = CookerSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        queryset = Cooker.objects.all()
        form = CookerSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class CookerDetailView(generic.DetailView):
    model = Cooker
    template_name = "restaurant/cook_detail.html"


class CookerCreationView(LoginRequiredMixin, generic.CreateView):
    model = Cooker
    form_class = CookerCreationForm
    template_name = "restaurant/cook_create.html"
    success_url = reverse_lazy("restaurant:index")


class DishListView(generic.ListView):
    model = Dish
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Dish.objects.all()
        form = DishSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class DishDetailView(generic.DetailView):
    model = Dish


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishCreationForm
    template_name = "restaurant/dish_create.html"
    success_url = reverse_lazy("restaurant:index")


class DishTypeListView(generic.ListView):
    model = DishType
    template_name = "restaurant/dish_type_list.html"
    context_object_name = "dish_type_list"
    paginate_by = 8


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    form_class = DishTypeCreationForm
    template_name = "restaurant/dish_type_create.html"
    success_url = reverse_lazy("restaurant:index")


class CookerUpdateView(generic.UpdateView):
    model = Cooker
    form_class = CookerDishesUpdateForm
    template_name = "restaurant/cook_update.html"
    success_url = reverse_lazy("restaurant:cook-list")


class DishUpdateView(generic.UpdateView):
    model = Dish
    form_class = DishUpdateForm
    template_name = "restaurant/dish_update.html"
    success_url = reverse_lazy("restaurant:dish-list")

templates/includes/footer-auth.html
<footer class="footer position-absolute bottom-2 py-2 w-100">
      <div class="container">
        <div class="row align-items-center justify-content-lg-between">
          <div class="col-12 col-md-6 my-auto">
            <div class="copyright text-center text-sm text-white text-lg-start">
              &copy; <a href="https://bit.ly/3fKQZaL" class="font-weight-bold text-white" target="_blank">Creative Tim</a>
              coded by AppSeed.
            </div>
          </div>
          <div class="col-12 col-md-6">
            <ul class="nav nav-footer justify-content-center justify-content-lg-end">
              <li class="nav-item">
                <a href="https://github.com/app-generator/django-material-kit" class="nav-link text-white" target="_blank">Sources</a>
              </li>
              <li class="nav-item">
                <a href="https://appseed.us/support" class="nav-link text-white" target="_blank">Support</a>
              </li>
              <li class="nav-item">
                <a href="https://appseed.us" class="nav-link text-white" target="_blank">AppSeed</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

templates/includes/footer-components.html
  <!-- -------- START FOOTER 3 w/ COMPANY DESCRIPTION WITH LINKS & SOCIAL ICONS & COPYRIGHT ------- -->
  <footer class="footer py-5">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mb-4 mx-auto text-center">
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Company
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            About Us
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Team
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Products
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Blog
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Pricing
          </a>
        </div>
        <div class="col-lg-8 mx-auto text-center mb-4 mt-2">
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-dribbble"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-twitter"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-instagram"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-pinterest"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-github"></span>
          </a>
        </div>
      </div>
      <div class="row">
        <div class="col-8 mx-auto text-center mt-1">
          <p class="mb-0 text-secondary">
            &copy; <a href="https://bit.ly/3fKQZaL" class="font-weight-bold" target="_blank">Creative Tim</a>
              coded by OleksandrGrk.
          </p>
        </div>
      </div>
    </div>
  </footer>
  <!-- -------- END FOOTER 3 w/ COMPANY DESCRIPTION WITH LINKS & SOCIAL ICONS & COPYRIGHT ------- -->

templates/includes/footer.html
  <footer class="footer pt-5 mt-5">
    <div class="container">
      <div class="row">
        <div class="col-md-3 mb-4 ms-auto">
          <div>
            <a href="https://appseed.us/product/django-material-kit">
              <img src="{{ ASSETS_ROOT }}/img/cooking.png" class="mb-3 footer-logo" alt="main_logo">
            </a>
            <h6 class="font-weight-bolder mb-4">MacMichelin</h6>
          </div>
          <div>
            <ul class="d-flex flex-row ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://www.facebook.com/CreativeTim" target="_blank">
                  <i class="fab fa-facebook text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://twitter.com/creativetim" target="_blank">
                  <i class="fab fa-twitter text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://dribbble.com/creativetim" target="_blank">
                  <i class="fab fa-dribbble text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://github.com/creativetimofficial" target="_blank">
                  <i class="fab fa-github text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://www.youtube.com/channel/UCVyTG4sCw-rOvB9oHkzZD1w" target="_blank">
                  <i class="fab fa-youtube text-lg opacity-8"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-4 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-sm">Company</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'restaurant:index' %}" target="_blank">
                  About Us
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'restaurant:cook-list' %}" target="_blank">
                  Cooks
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'restaurant:dish-list' %}" target="_blank">
                  Dishes
                </a>
              </li>

            </ul>
          </div>
        </div>
        <div class="col-md-4 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-sm">Resources</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="" target="_blank">
                  Delivery
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="" target="_blank">
                  News
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="" target="_blank">
                  Booking
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-12">
          <div class="text-center">
            <p class="text-dark my-4 text-sm font-weight-normal">
              &copy; <a href="https://bit.ly/3fKQZaL" class="font-weight-bold" target="_blank">Creative Tim</a> 
              coded by <a href="https://appseed.us" class="font-weight-bold" target="_blank">OleksandrGrk</a>.
            </p>
          </div>
        </div>
      </div>
    </div>
  </footer>

templates/includes/navigation.html
  <!-- Navbar -->
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur border-radius-xl mt-4 top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid px-0">
            <a class="navbar-brand font-weight-bolder ms-sm-3" href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
              MacMichelin
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
              <ul class="navbar-nav navbar-nav-hover ms-auto">
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">
                    Pages
                    <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-auto ms-md-2">
                  </a>
                  <div class="dropdown-menu dropdown-menu-animation ms-n3 dropdown-md p-3 border-radius-xl mt-0 mt-lg-3" aria-labelledby="dropdownMenuPages">
                    <div class="d-none d-lg-block">
                      <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1">
                        Our restaurant
                      </h6>
                      <a href="{% url 'restaurant:index' %}" class="dropdown-item border-radius-md">
                        <span>About Us</span>
                      </a>
                      <a href="{% url 'restaurant:cook-list' %}" class="dropdown-item border-radius-md">
                        <span>Cooks</span>
                      </a>
                      <a href="{% url 'restaurant:dish-list' %}" class="dropdown-item border-radius-md">
                        <span>Dishes</span>
                      </a>
                      <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1 mt-3">
                        Account
                      </h6>
                      <a href="{% url 'login' %}" class="dropdown-item border-radius-md">
                        <span>Sign In</span>
                      </a>
                    </div>
                  </div>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" id="dropdownMenuBlocks" data-bs-toggle="dropdown" aria-expanded="false">
                    Add new
                    <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-auto ms-md-2">
                  </a>
                  <ul class="dropdown-menu dropdown-menu-end dropdown-menu-animation dropdown-md dropdown-md-responsive p-3 border-radius-lg mt-0 mt-lg-3" aria-labelledby="dropdownMenuBlocks">
                    <div class="d-none d-lg-block">
                      <li class="nav-item dropdown dropdown-hover dropdown-subitem">
                        <div class="dropdown-item py-2 ps-3 border-radius-md">
                          <div class="w-100 d-flex align-items-center justify-content-between">
                            <div>
                              <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">Create pages</h6>
                              <span class="text-sm">Make something new!</span>
                            </div>
                            <img src="{{ ASSETS_ROOT }}/img/down-arrow.svg" alt="down-arrow" class="arrow">
                          </div>
                        </div>
                        <div class="dropdown-menu mt-0 py-3 px-2 mt-3">
                          <a class="dropdown-item ps-3 border-radius-md mb-1" href="{% url 'restaurant:cook-create' %}">
                            Create Cook
                          </a>
                          <a class="dropdown-item ps-3 border-radius-md mb-1" href="{% url 'restaurant:dish-create' %}">
                            Create Dish
                          </a>
                        </div>
                      </li>
                    </div>
                  </ul>
                </li>
                {% endif %}

                {% if request.user.is_authenticated %}
                  <li class="nav-item ms-lg-auto">
                    <a class="nav-link nav-link-icon me-2" 
                      href="{% url 'logout' %}">
                      <i class="fa fa-sign-out me-1"></i>
                      <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Sign OUT">Logout</p>
                    </a>
                  </li>          
                {% endif %}

              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
<div class="container">
  <div class="row">
    <div class="col-4"></div>
    <div class="col-6">
      <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item active">
          <a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number%}">{{ page_obj.previous_page_number }}</a>
        </li>
      {% endif %}
        <li class="page-item">
          <div class="page-link">{{ page_obj.number }}</div>
        </li>
      {% if page_obj.has_next %}
        <li class="page-item active">
          <a class="page-link" href="?{% query_transform request page=page_obj.next_page_number%}">{{ page_obj.next_page_number }}</a>
        </li>
      {% endif %}
      </ul>
    </div>

  </div>
</div>

{% endif %}

templates/restaurant/cook_create.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <p>Creation form</p>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="bth btn-primary">
  </form>
{% endblock %}

templates/restaurant/cook_detail.html
{% extends "layouts/base.html" %}

{% block content %}

  {% include 'includes/navigation-transparent.html' %}
  <header class="header-2">
    <div class="page-header min-vh-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/{{ cooker.first_name.lower}}_{{ cooker.last_name.lower}}.jpg')">
      <span class="mask bg-gradient-dark opacity-6"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
            <h1 class="text-white">{{ cooker.get_full_name }}</h1>
            <h6 class="text-white mb-2 mt-5">{{ cooker.years_of_experience }} year{{ cooker.years_of_experience|pluralize}} in cooking!</h6>
            <div class="d-flex justify-content-center">
              <a href="javascript:;"><i class="fab fa-facebook text-lg text-white me-4"></i></a>
              <a href="javascript:;"><i class="fab fa-instagram text-lg text-white me-4"></i></a>
              <a href="javascript:;"><i class="fab fa-twitter text-lg text-white me-4"></i></a>
              <a href="javascript:;"><i class="fab fa-google-plus text-lg text-white"></i></a>
              <a href="{% url 'restaurant:cook-update' pk=cooker.id %}" class="btn btn-secondary link-to-page">
              Update Cook`s username
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>

  {% for dish in cooker.dishes.all %}
  <section class="my-5 py-5">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-4 ms-auto me-auto p-lg-4 mt-lg-0 mt-4">
            <div class="rotating-card-container">
              <div class="card card-rotate card-background card-background-mask-primary shadow-primary mt-md-0 mt-5">
                <div class="front front-background" style="background-image: url('{{ ASSETS_ROOT }}/img/{{ dish.name.lower }}.jpg'); background-size: cover;">
                  <div class="card-body py-7 text-center">
                    <i class="material-icons text-white text-4xl my-3">touch_app</i>
                    <h3 class="text-white">Try the best {{ dish.name }}</h3>
                    <p class="text-white opacity-8">Price: {{ dish.price}} $</p>
                  </div>
                </div>
                <div class="back back-background" style="background-image: url('{{ ASSETS_ROOT }}/img/{{ dish.name.lower }}.jpg'); background-size: cover;">
                  <div class="card-body pt-7 text-center">
                    <h3 class="text-white">{{ dish.dish_type}}</h3>
                    <p class="text-white opacity-8">{{ dish.description }}</p>
                    <a href="{% url 'restaurant:dish-detail' pk=dish.id %}" class="btn btn-white btn-sm w-50 mx-auto mt-3">Read more</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  {% endfor %}
{% endblock %}

templates/restaurant/cook_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}


{% block content %}
{% include 'includes/navigation-transparent.html' %}

<header class="header-2">
    <div class="page-header min-vh-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/bg-dish-list.jpg')">
      <span class="mask bg-gradient-dark opacity-6"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
            <h1 class="text-center text-white">OUR COOKS</h1>
              {% if cooker_list %}
                {% for cooker in cooker_list %}
                  <img width="45%" height="auto" src="{{ ASSETS_ROOT }}/img/{{ cooker.first_name.lower }}_{{cooker.last_name.lower}}.jpg" alt="">
                  <a href="{{ cooker.get_absolute_url }}">
                    <p style="color: white">{{ cooker.first_name }} {{cooker.last_name}}</p>
                  </a>
                {% endfor %}
                {% else %}
                  <p>There are no dishes available</p>
              {% endif %}
          </div>
        </div>
      </div>
    </div>
  </header>

  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
  <input class="btn btn-secondary" type="submit" value="search">
  </form>
  {% block pagination %}
    {% include "includes/pagination.html" %}
  {% endblock %}

{% endblock %}

templates/restaurant/cook_update.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}

<section>
  <div class="container py-4">
    <div class="row">
      <div class="col-lg-7 mx-auto d-flex justify-content-center flex-column">
        <h3 class="text-center">Update cook`s username</h3>
        <form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form|crispy }}
  <input type="submit" value="Submit" class="btn btn-primary">
</form>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/restaurant/dish_detail.html
{% extends "layouts/base.html" %}

{% block content %}
  <h1>{{ dish.name }} detail</h1>
  <img rel="icon" width="100%" height="auto" src="{{ ASSETS_ROOT }}/img/{{ dish.name.lower }}.jpg">
  <p>Price: {{ dish.price }}</p>
  <a href="{% url 'restaurant:dish-update' pk=dish.id %}" class="btn btn-danger link-to-page">
    Update dish`s price
  </a>
  <p>Description: {{ dish.description }}</p>
  <p>Dish type: {{ dish.dish_type}}</p>
  <h3>Available cooks:</h3>
  {% for cook in dish.cooks.all %}
    <a href="{{ cook.get_absolute_url }}">
      <li>{{ cook.get_full_name }}</li>
    </a>
  {% endfor %}
{% endblock %}

templates/restaurant/dish_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
{% include 'includes/navigation-transparent.html' %}
<header class="header-2">
  <div class="page-header min-vh-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/bg-dish-list.jpg')">
    <span class="mask bg-gradient-dark opacity-6"></span>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center mx-auto my-auto">
          <h1 class="text-white mb-2 mt-5">Dish List</h1>
            {% if dish_list %}
              <ul style="list-style-type: none">
                {% for dish in dish_list %}
                  <li>
                    <a href="{% url 'restaurant:dish-detail' pk=dish.id %}" style="color: white">
                      {{ dish.name }}
                      - {{ dish.price }}
                    </a>
                  </li>
                {% endfor %}
              </ul>
            {% else %}
              <p>There are no dishes available</p>
            {% endif %}
        </div>
      </div>
    </div>
  </div>
</header>

<form action="" method="get" class="form-inline">
  {{ search_form|crispy }}
<input class="btn btn-secondary" type="submit" value="search">
</form>
{% block pagination %}
  {% include "includes/pagination.html" %}
{% endblock %}

{% endblock %}